<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Web01.aspx.cs" Inherits="Project01.Tasks.Web01" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Web01</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <h1>CHARUSAT UNIVERSITY</h1>
            <nav class="navbar navbar-expand-lg navbar-light bg-dark rounded">
                <asp:HyperLink ID="hlHome" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#" Target="_self">Home</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlAbout" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#About" Target="_self">About University</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlCourses" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#Courses">Courses</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlDepartments" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#Departments" Target="_self">Departments</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlStaff" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#Staff" Target="_self">Staff Members</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlNews" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#News" Target="_self">News</asp:HyperLink>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="hlContact" runat="server" CssClass="navbar-brand text-white" NavigateUrl="#Contact" Target="_self">Contact</asp:HyperLink>
            </nav>
            <h2>&nbsp;</h2>
            <h2>&nbsp;</h2>
            <h2 id="About">About University</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

            <h2 id="Courses">Courses</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

            <h2 id="Departments">Departments</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

            <h2 id="Staff">Staff Members</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

            <h2 id="News">News</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

            <h2 id="Contact">Contact</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

        </div>
    </form>
</body>
</html>
