<%@ Page Title="" Language="C#" MasterPageFile="~/Content/DemoMaster.Master" AutoEventWireup="true" CodeBehind="AboutPage.aspx.cs" Inherits="Project01.WebWithMasterPage.WebForm1" %>


<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" runat="server">
</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="cphMainContent" runat="server">
    <h2>About Us</h2>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>
            <p>Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.Charotar University of Science and Technology (CHARUSAT) is a State Private University established under the Gujarat Act No. 8 of 1995, Government of Gujarat. The University is recognized by University Grants Commission (UGC) under Section 22 of UGC Act 1956 and accredited with grade A by NAAC in 2016.</p>

</asp:Content>
